[project]
name = "ht6"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4.0"
dependencies = [
    "poetry>=2.1.3",
    "matplotlib (==3.10.3)",
    "networkx (==3.4.2)",
]
